feat: финальное задание спринта 10
grand1964/java-filmorate pull request #3
Opened 2023-05-19 15:33 UTC by grand1964

Добавлена возможность объединять пользователей и ставить лайки фильмам.

2023-05-20 15:30 UTC, NikolaiDem requested changes

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Одинаковые обработки исключений можно объединить в один метод. Для этого можно указать типы исключений, обрабатываемых в методе. Например,
@ExceptionHandler({ValidateException.class, MethodArgumentNotValidException.class})
Аналогиччно для остальных методов

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(required = false, defaultValue = "10") String count) {
При указание дефолтного значения "required = false" лишнее )

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void addLike(@PathVariable Map<String, String> params) {
Указание переменных отдельно выглядит более лаконично )
@PathVariable String id, @PathVariable String userId

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film deleteLike(@PathVariable Map<String, String> params) {
Указание переменных отдельно выглядит более лаконично )
@PathVariable String id, @PathVariable String userId

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<User> getCommonFriends(@PathVariable Map<String, String> params) {
Указание переменных отдельно выглядит более лаконично )
@PathVariable String id, @PathVariable String otherId
Аналогично для addFriend(...) и deleteFriend(...)

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @RestController
"/films" можно вынести на уровень контроллера
@RequestMapping("/films")

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  @RestController
"/users" можно вынести на уровень контроллера
@RequestMapping("/users")

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    // геттеры необходимы, чтобы Spring Boot мог получить значения полей
Геттеры можно добавить с помощью lombok

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/AbstractService.java
> +        log = LoggerFactory.getLogger(getClass());
Статические поля существуют в единственном экземпляре для всех объектов. Поэтому лучше или убрать static или   убрать log из конструктора.

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/AbstractService.java
> +            return Long.parseLong(paramId);
Лучше в параметре метода контроллера сразу указать Long id вместо String id, чтобы узнать о возможной проблеме как можно раньше

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/AbstractService.java
> +    protected long validateId(String paramId) {
Название метода не соответствует тому, что он делает, более подходящее parseId

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/AbstractService.java
> +        return outObject.orElseThrow();
Можно упростить
        return outObject.orElseThrow(() -> {
            log.error("Объект с идентификатором " + object.getId() + " уже существует.");
            return new ObjectAlreadyExistException(object.getId());
        });
Аналогично для остальных методов

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        long userId = validateUserId(userParam);
validateUserId(...) никогда же не возвращает -1

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return id;
id выполняет имеет 2 роли : как идентификатор объекта и как идентификатор ошибки. От неоднозначности параметров лучше избавиться, у него должно быть только одно предназначение. 
Вместо возвращения -1 лучше сразу бросать исключение
Аналогично для всех сервисов.

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.error(String.format("Не найден фильм с идентификатором " + paramId));
Для чего format?

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = storage.get(filmId).orElseThrow();
Пустые исключения orElseThrow() лучше не использовать, необходимо добавить детали ошибки 
Аналогично для всех методов

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.info("Пользователь " + userId + " удалил лайк с фильма " + filmId);
Почему лог идет до выполнения удаления?

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getTopFilms(String count) {
Валидацию на числовое значение параметра лучше сделать на уровне контроллера, чтобы найти возможную ошибку как можно раньше

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/ImMemoryFilmStorage.java
> +        if (film.getLikes() == null) { //список лайков не инициализирован
Лучше сделать так, чтобы film.getLikes() никогда не возвращал null (перенести проверки в Film)

2023-05-20 15:30 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getFriends() == null) { //список друзей не инициализирован
Лучше сделать так, чтобы user.getFriends() никогда не возвращал null (перенести проверки в User)

2023-05-21 16:29 UTC, grand1964 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = storage.get(filmId).orElseThrow();
Привет, Николай! Здесь исключения быть не может. Я бы заменил orElseThrow на get, но IDEA на это ругается.

2023-05-21 23:11 UTC, NikolaiDem requested changes

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilm(@PathVariable("id") String filmId) {
Можно сразу long указать.
Аналогично для остальных методов

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User getUser(@PathVariable("id") String userId) {
Можно сразу long указать.
Аналогично для остальных методов

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      public User updateUser(@RequestBody User user) {
А @Valid?

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (storage.get(filmId).orElseThrow().getLikes().add(userId)) {
Выглядит как не совсем подходящее использование Optional. 
validateFimId(...) и validateFimId(...) тогда не нужны, а возможные ошибки прописать в orElseThrow(...)

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (storage.get(filmId).orElseThrow().getLikes().add(userId)) {
Лучше не раскрывать детали реализации хранения лайков, метод addLike(...) добавить в Film )

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.getLikes().remove(userId);
Лучше не раскрывать детали реализации хранения лайков, метод removeLike(...) добавить в Film )

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(defaultValue = "10") String count) {
Можно добавить @PositiveOrZero, чтобы сразу выбросить ошибку, если count не положительное. Еще на уровне класса добавить аннотацию @Validated

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userId <= 0) {
Сервис не должен знать о деталях реализации репозитория

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (release.isBefore(BASE_DATE)) {
Еще нужна проверка на null

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!storage.get(userId).orElseThrow().getFriends().add(friendId)) {
Выглядит как не совсем подходящее использование Optional.
validateFimId(...) и validateFimId(...) тогда не нужны, а возможные ошибки прописать в orElseThrow(...)

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user1 = storage.get(id1).orElseThrow();
Избавиться от рудиментарных orElseThrow(). Аналогично для остальных методов.
Или, например, так:
        User user1 = storage.get(id1).orElseThrow(() -> new ObjectNotExistException(id1));

2023-05-21 23:11 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public static <T> Set<T> intersection(Set<T> set1, Set<T> set2) {
private

2023-05-22 11:10 UTC, grand1964 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userId <= 0) {
Привет, Николай! Я не понимаю, как исправить это место. Если вообще убрать проверку userId - падает последний тест в постмане. Проверить валидность userId нельзя, поскольку нет доступа к хранилищу юзеров. Можно внедрить это хранилище в FilmService. Но это создаст проблему с дженериком, да и по сути странное решение. Напиши, пожалуйста, подробнее, что ты имел в виду в этом замечании.

2023-05-23 08:39 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userId <= 0) {
Андрей, привет!
О валидности id должен знать репозиторий. В случае некорректного id репозиторий вернет пустой Optional, и сервис выбросит исключение)

2023-05-23 08:40 UTC, NikolaiDem approved these changes

2023-05-23 09:58 UTC, merged