feat: финальное задание спринта 11
grand1964/java-filmorate pull request #4
Opened 2023-06-09 15:00 UTC by grand1964

Добавлено постоянное хранение данных в базе H2.

2023-06-10 13:51 UTC, NikolaiDem requested changes

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping(value = "/genres")
Эндпоинты для жанров и рейтингов лучше вынести в 2 отдельных контроллера

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +@Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.
Аналогично для всех классов моделей.

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +public class Genre {
Все поля private.
Аналогично для всех классов моделей.

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            loadUserFriends(user);
Проблема N+1 запроса. Одним запросом получены все юзеры, и для каждого делается запрос в БД для получения его друзей (то есть для N юзеров еще N запросов). Такого поведения необходимо избегать, лучше получить всех друзей для всех пользователей тоже одним запросом. Можно сконструировать селект из friends с джойном к users. В таком селекте у нас каждая строка из ответа будет содержать id пользователя, id друга и данные о друге (из таблицы users), можем идти по каждой такой строке, создавать друга и добавлять его пользователю, это можно сделать с помощью метода
void query(String sql, RowCallbackHandler rch), 
где RowCallbackHandler  - обработчик каждой строки из нашего селекта.

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        storage.deleteAllFriends(id); //удаляем из базы всех друзей пользователя
Для обновления друзей лучше использовать существующие эндпоинты addFriend/deleteFriend. А метод updateUser(...) обновит только данные пользователя

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +    public Optional<Genre> getGenre(long genreId) {
Для жанров и рейтингов лучше создать отдельные репозитории

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +                "inner join friends as fu on uf.user_id = :user_id and fu.friend_id = :user_id " +
uf.user_id = :user_id and fu.friend_id = :user_id лучше перенести в where, а условие из where в on. Результат будет таким же, но логически более правильно в on указывать условие как надо соединять таблицы, а в where что оставить в результирующей выборке

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +                "where u.id in (select uf.friend_id from friends as uf " +
Вложенный селект лучше заменить джойном

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbUserStorage.java
> +                "where u.id in (select f1.friend_id from friends as f1 " +
Вложенный селект лучше заменить джойном

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    //////////////////////////// Поддержка лайков ////////////////////////////
////////////////////////////......//////////////////////////// явно указывает на разделение FilmStorage в 3 репозитория

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    boolean addFriend(long userId, long friendId);
Все методы очень похожи на методы нового репозитория FriendRepository

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    mpa_id INTEGER,
И можно добавить constraint по внешнему ключу на mpa_id

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    user_id INTEGER,
И можно добавить constraint по внешнему ключу на user_id

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    genre_id INTEGER,
И можно добавить constraint по внешнему ключу на genre_id

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            loadFilmLinks(film);
Проблема N+1 запроса аналогично друзьям.
И так же для getTopFilms(...)

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                storage.addFilmGenre(film.getId(), genre.getId());
Для множественного обновления лучше использовать jdbcTemplate.batchUpdate(String sql, final BatchPreparedStatementSetter pss), чтобы сделать это одним запросом.

2023-06-10 13:51 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            storage.addLike(filmId, id); //добавляем лайк фильму
От запросов в цикле лучше избавиться и выполнить необходимые действия за один запрос к БД

2023-06-17 07:02 UTC, grand1964 commented on src/main/resources/schema.sql
> +    user_id INTEGER,
Вначале так и было. Но тесты в Postman не считают ошибкой лайк от несуществующего юзера (единственное требование - его id должен быть положительным). А при ограничении внешнего ключа лайк может ставить только реальный пользователь, иначе будет исключение. Та же проблема и с предыдущим замечанием: если у фильма нет mpa, то произойдет ошибка.

2023-06-17 23:57 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            loadFilmLinks(film);
Не исправлено

2023-06-17 23:58 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        storage.deleteAllFriends(id); //удаляем из базы всех друзей пользователя
Не исправлено

2023-06-18 00:04 UTC, NikolaiDem requested changes
Андрей, необходимо починить сборку

2023-06-19 19:26 UTC, NikolaiDem requested changes

2023-06-19 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Validated
Лишнее, потому что нет аннотаций валидации )

2023-06-19 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@Validated
Лишнее, потому что нет аннотаций валидации )

2023-06-19 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static void storeFullRow(ResultSet rs, Map<Long, Film> map) throws SQLException {
Этот метод больше похож на метод сервиса, потому что один из аргументов - это все прочитанные фильмы, которые постоянно передаются в метод

2023-06-19 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Genre getGenre(long genreId) {
Методы getGenre и getAllGenres больше относятся к сервису GenreService.
Аналогично для mpa

2023-06-19 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            if ((genre == null) || genreStorage.getGenre(genre.getId()).isEmpty()) {
Проблема N+1 запроса. Не нужно в каждой итерации обращаться к genreStorage

2023-06-19 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private void validateUserId(long id) {
Валидацию id лучше заменить @Positive в методе контроллера )

2023-06-19 19:26 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void validate(Film film) {
Актуализировать кастомные проверки : большая часть валидации выполняется через аннотации валидации (NotBlank, NotNull, Min и т.д.). Тогда ручные проверки можно удалить )

2023-06-19 19:26 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    user_id INTEGER,
Какой тест падает, если добавляется constraaint?

2023-06-20 09:07 UTC, grand1964 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static void storeFullRow(ResultSet rs, Map<Long, Film> map) throws SQLException {
Этот метод нужен и в FilmStorage, и в LikeStorage. Если убрать его из Film, то придется его дублировать в этих классах или создавать для них общего предка. К чему такие сложности?

2023-06-20 09:07 UTC, grand1964 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Genre getGenre(long genreId) {
У меня есть только FilmService. Ты предлагаешь выделить из него getGenre и getAllGenres? Но к ним все равно придется обращаться из FilmService, так какой смысл? Только получим еще одну порцию наведенных ошибок.

2023-06-20 09:08 UTC, grand1964 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private void validateUserId(long id) {
Проверил, плохо: к @Positive у меня привязана ошибка 400, а тесты ждут 404. А если поменять - упадет где-нибудь в другом месте. Тяжело все время маневрировать между Харибдой и Сциллой :)

2023-06-20 09:08 UTC, grand1964 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void validate(Film film) {
Не понял этого замечания. Если ты про жанры и mpa, то там ручная проверка содержательная, ее аннотациями не заменишь (да и что в этих классах аннотировать?). А в Film все, что можно, проверяется по аннотациям, и вроде к этому месту претензий раньше не было.

2023-06-20 15:24 UTC, NikolaiDem approved these changes

2023-06-21 12:53 UTC, merged